# Generated by Django 3.1.1 on 2020-09-23 09:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=15)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('localizador', models.CharField(max_length=15)),
                ('fecha_entrada', models.DateField(default=datetime.date.today)),
                ('fecha_salida', models.DateField(default=datetime.date.today)),
                ('n_huespedes', models.IntegerField()),
                ('huesped_nombre', models.CharField(max_length=100)),
                ('huesped_email', models.EmailField(max_length=100)),
                ('huesped_telefono', models.CharField(max_length=30)),
                ('precio_total', models.FloatField()),
                ('n_habitacion', models.CharField(max_length=3)),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscadorApp.habitacion')),
            ],
        ),
    ]
