# Generated by Django 3.1.1 on 2020-09-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscadorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
