# Generated by Django 3.1.1 on 2020-09-23 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buscadorApp', '0002_auto_20200923_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroHabitaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('n_habitaciones', models.IntegerField(default=0)),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscadorApp.habitacion')),
            ],
        ),
    ]
