# Generated by Django 3.1.1 on 2020-09-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscadorApp', '0003_numerohabitaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_entrada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_salida',
            field=models.DateTimeField(),
        ),
    ]
