# Generated by Django 3.1.1 on 2020-09-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscadorApp', '0005_auto_20200924_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='n_habitacion',
        ),
    ]
