# Generated by Django 3.1.1 on 2020-09-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buscadorApp', '0007_auto_20200924_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='cantidad',
        ),
    ]
